project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Introduction to R Training - July 2025"
  author: "The Intro to R Team"
  date: today
  date-format: long
  navbar:
    search: true
    pinned: true
    right:
      - icon: github
        href: https://github.com/EMRR-DISE/IntrotoR
        aria-label: GitHub
  chapters:
    - index.qmd
    - part: code/Day1_01_Intro.qmd
      chapters:
        - code/Day1_02_Objects.qmd
        - code/Day1_03_Packages.qmd
        - code/Day1_04_ErrorsHelp.qmd
    - part: code/Day2_01_Intro.qmd
      chapters:
        - code/Day2_02_Subset.qmd
        - code/Day2_03_Mutate.qmd
        - code/Day2_04_Summarize.qmd
    - part: "Day 3 - Visualizing Data"
      chapters:
        - code/Day3_MakingGraphs.qmd
    - part: code/Day4_01_Outline.qmd
      chapters:
        - code/Day4_02_Joins_Binds.qmd
        - code/Day4_03_Dates_and_Times.qmd
        - code/Day4_04_Final_Exercise.qmd
  appendices:
    - code/MarkdownFiles.qmd
    - code/RDefinitions.qmd
    - code/Resources.qmd

format:
  html:
    theme: cosmo
    toc-depth: 4
    toc-expand: 2

