---
title: "meeting notes"
author: "Rosie"
date: "2024-02-07"
output: html_document
---
## Initial discussion of R training

Attendance:
* Dave Bosworth
* Nick
* Ted Swift
* Perry
* Rosie

### Tentative course outline

Pick a dataset to work on. Just messy enough, not enough to slow us down. 
	• Tour of R and Rstudio - Rosie
		○ consule, 
		○ environment, 
		○ Scripts
		○ Packages/libraries
		○ Projects, working directory, file organization
	• Intro to the command line. 
		○ Basic calculations
		○ Variable assignment
		○ How to use a function (and how to read the help section)
	• Getting help and resources for teaching youreslf
		○ Error messages, difference between warnings and errors
		○ Help documentation
		○ R studio autocomplete, cheatsheets
	• Data processing and organization - Perry
		○ Data types - numbers, characters, factors, date/time, others
			§ Str(), glimpse(), head()
		○ Data formats - vectors, matricies, lists, data frames
		○ Importing data
		○ Selecting/subsetting data
		○ Exporting data
		- If we do joins
	• Basic graphs - Nick
		Histogrmas
		Line graphs
		Bar graphs
		scatterplots
	• Basic statistics  (if time) - Bos. 
		○ Summary stats - mean, median, max, min
		○ Group_by and summarize
		- Demo with a different dataset
		- Don't try and cram in anovas and stuff, just the summary stats. 
		
	_ mini topics to throw in if time allows
	* Joins
	* Bind rows, bind columns
	* Pivoting longer and wider

Ted will finangle setup, software install, sign ups. 

Intermediate class
	-  regressions and anova
	- Data restructuring
	- Loops/apply
	- pivot
	- Joins, binds
	- Group_by and summarize
	- Writing functions
	- Style guide
	- Advanced graphs
	- If…else…. (case_when!)
	- Tidyselect
	- Dates and time
	- Broom
	- maps

Previous classes were 2-days over 2-weeks
	
Resources we can borrow from:
	- https://www.r4wrds.com/intro/
	- https://intro2r.com/
	- https://www.codecademy.com/learn/learn-r
	- Data camp: https://app.datacamp.com/ 
	- https://rstudio-education.github.io/hopr/
	

Logistics
	- Ted to get registration, previous classes had over 70 people, interested
	- Probably 30 or so people per class.  
	- Markdown tutorial.


## Follow up 4/29

Dates

- Tuesday, July 9th, Day 1 – Tour or R, Intro to the command line, intro to how to read error messages and documentation (Rosie to lead, others to TA as available)
- Thursday, July 11th – Day 2 - data organization/ import and export, subsetting, etc (Perry to lead, others to TA)
- Tuesday, July 16th – Day 3 – Introduction to graphing (Nick)
- Thursday, July 18th – Day 4 – Intro to stats (Boz)

Time 

10:00-12:00, 1:00-3:00 each day

To decide today:
- Do we want to cap registration? - 30
- What dataset do we want to use?-
* WQ from fall of 2021?
* Maybe two EMP stations that are really different - D7 and P8
* Flow? Dayflow or a CDEC flow variable?

Make recording available.

## Meeting 5/20

Registration - how's it going?
- 8 so far
Dataset - water quality D7 and P8.

Day 2
- Importing data
- exporting data
- 'here' package and navigating to stuff
- sort/arranging
- subsetting - select, rename
- mutating
- Maybe joins if time allows
- Maybe some more advanced functions

Day 3
- Graphs

Day 4
- Group_by and summarize
- Restructuring - pivot wider and longer
- left_join - nothing more complicated
- Final project - new dataset. Maybe dayflow? Or splittail counts from Yolo?


